/*
 * IndexerService.h
 */

#ifndef INDEXER_SERVICE_H
#define INDEXER_SERVICE_H

#include <stdint.h>

#include "ES_Configure.h"
#include "ES_Events.h"
#include "RC_Servo.h"

/*
 * Indexer output is generated by RC_Servo on PortZ-04 so PortZ-06 can be used
 * by the secondary shooter hardware PWM.
 */
#ifndef INDEXER_RC_PIN
#define INDEXER_RC_PIN RC_PORTZ04
#endif

#ifndef INDEXER_OUTPUT_PIN_NAME
#define INDEXER_OUTPUT_PIN_NAME "PortZ-04"
#endif

#ifndef INDEXER_PWM_PIN_NAME
#define INDEXER_PWM_PIN_NAME INDEXER_OUTPUT_PIN_NAME
#endif

#ifndef INDEXER_STARTUP_PULSE_US
#define INDEXER_STARTUP_PULSE_US MAXPULSE
#endif

#ifndef INDEXER_RUN_PULSE_US
#define INDEXER_RUN_PULSE_US 1250
#endif

#ifndef INDEXER_STARTUP_TIME_MS
#define INDEXER_STARTUP_TIME_MS 500
#endif

uint8_t InitIndexerService(uint8_t priority);
uint8_t PostIndexerService(ES_Event thisEvent);
ES_Event RunIndexerService(ES_Event thisEvent);

uint8_t StartIndexerSystem(void);
uint8_t StopIndexerSystem(void);

#endif /* INDEXER_SERVICE_H */
