/*
 * Compatibility wrapper for older MPLAB-generated project metadata.
 * New code should compile ShooterService.c directly when project metadata is
 * regenerated by MPLAB X.
 */

#include "ShooterService.c"
